### ISSUE TITLE
アカウントがない状態でログインしようとするとエラーが出る

### ISSUE THREAD

**Issue by saitolume** [saitoeku3/kit-web-application#16]
> PDOException: SQLSTATE[HY000] [2002] Connection refused in /app/db/connect.php:11 Stack trace: #0 /app/db/connect.php(11): PDO->__construct('mysql:host=127....', NULL, NULL) #1 /app/app/controllers/ApplicationController.php(7): connect_db() #2 /app/app/controllers/SessionsController.php(40): ApplicationController->connect_db() #3 /app/app/controllers/SessionsController.php(22): SessionsController->authentication('saitoeku3@gmail...', 'password') #4 /app/index.php(23): SessionsController->create(Array) #5 {main}

**Comment by saitolume** [comment]
本番環境で MySQL が有効化できていないからっぽい
